//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haden.NXTRemote.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Haden.NXTRemote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Common__NumberZero {
            get {
                return ResourceManager.GetString("Common__NumberZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string Generic_Click_Connection_error {
            get {
                return ResourceManager.GetString("Generic_Click_Connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NXT Brick is not available.
        /// </summary>
        internal static string Generic_NXT_Brick_not_available {
            get {
                return ResourceManager.GetString("Generic_NXT_Brick_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous controller &apos;haden&apos; Copyright 2003 - 2025 Cartheur Research, B.V..
        /// </summary>
        internal static string HadenControlForm_aboutToolStripMenuItem_About {
            get {
                return ResourceManager.GetString("HadenControlForm_aboutToolStripMenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About m.e....
        /// </summary>
        internal static string HadenControlForm_aboutToolStripMenuItem_Click_AboutText {
            get {
                return ResourceManager.GetString("HadenControlForm_aboutToolStripMenuItem_Click_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string HadenControlForm_hyphen {
            get {
                return ResourceManager.GetString("HadenControlForm_hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a phrase to voice..
        /// </summary>
        internal static string HadenControlForm_Please_select_a_phrase_to_voice {
            get {
                return ResourceManager.GetString("HadenControlForm_Please_select_a_phrase_to_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot connected..
        /// </summary>
        internal static string HadenControlForm_Robot_connected {
            get {
                return ResourceManager.GetString("HadenControlForm_Robot_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot disconnected..
        /// </summary>
        internal static string HadenControlForm_Robot_disconnected {
            get {
                return ResourceManager.GetString("HadenControlForm_Robot_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice error.
        /// </summary>
        internal static string HadenControlForm_Voice_Error {
            get {
                return ResourceManager.GetString("HadenControlForm_Voice_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of haden not yet implemented..
        /// </summary>
        internal static string HadenManualControl_statusToolStripMenuItem_Click_Status_implemented_ {
            get {
                return ResourceManager.GetString("HadenManualControl_statusToolStripMenuItem_Click_Status_implemented_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of device.
        /// </summary>
        internal static string HadenManualControl_statusToolStripMenuItem_Click_Status_of_device {
            get {
                return ResourceManager.GetString("HadenManualControl_statusToolStripMenuItem_Click_Status_of_device", resourceCulture);
            }
        }
    }
}
